// Code generated by pg. DO NOT EDIT.
package definition

// Event is a struct value that represents a record in the events table.
var Event = struct {
	PG_TableName string
	Id           Column
	CreatedAt    Column
	UpdatedAt    Column
	Title        Column
	Description  Column
}{
	PG_TableName: "events",
	Id: Column{
		Name: "id",
	},
	CreatedAt: Column{
		Name: "created_at",
	},
	UpdatedAt: Column{
		Name: "updated_at",
	},
	Title: Column{
		Name: "title",
	},
	Description: Column{
		Name: "description",
	},
}
