// Code generated by pg. DO NOT EDIT.
package definition

// User is a struct value that represents a record in the users table.
var User = struct {
	PG_TableName string
	Id           Column
	CreatedAt    Column
	UpdatedAt    Column
	Email        Column
	Password     Column
	FirstName    Column
	MiddleName   Column
	LastName     Column
	Sex          Column
}{
	PG_TableName: "users",
	Id: Column{
		Name: "id",
	},
	CreatedAt: Column{
		Name: "created_at",
	},
	UpdatedAt: Column{
		Name: "updated_at",
	},
	Email: Column{
		Name: "email",
	},
	Password: Column{
		Name: "password",
	},
	FirstName: Column{
		Name: "first_name",
	},
	MiddleName: Column{
		Name: "middle_name",
	},
	LastName: Column{
		Name: "last_name",
	},
	Sex: Column{
		Name: "sex",
	},
}
